apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  labels:
    app: simple-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
        - name: simple-nginx
          image: simple-nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
