apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  # Use a different type if LoadBalancer is not supported on your k8s environment
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: simple-nginx
